/**
 * Universal UPIF Worker
 * DPID: DPID-ORC-UPF-001
 * Port: 3078
 * Ecosystem: NEXUS (Central Hub)
 *
 * Universal Participant Identity Framework — the identity backbone of
 * the Trancendos Universe. Every human, AI agent, device, and entity
 * in the ecosystem has a UPIF identity that tracks their contributions,
 * capabilities, reputation, and agentic GDP participation.
 *
 * Core capabilities:
 * - Universal identity issuance (human + AI + IoT + synthetic)
 * - Cross-location identity resolution (L01-L23)
 * - Biometric identity anchoring (with BER Engine integration)
 * - Agentic GDP contribution tracking (per participant)
 * - Reputation scoring (multi-dimensional)
 * - Identity federation across all 6 Pillars
 * - L402 payment capability attestation
 */

import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { logger } from 'hono/logger';
import { z } from 'zod';

// ── Types ────────────────────────────────────────────────────────────────────

type EntityType = 'HUMAN' | 'AI_AGENT' | 'IOT_DEVICE' | 'SYNTHETIC' | 'ORGANISATION' | 'ECOSYSTEM';
type IdentityTier = 'BASIC' | 'VERIFIED' | 'TRUSTED' | 'SOVEREIGN' | 'UNIVERSAL';
type PillarAccess = 'PIL1' | 'PIL2' | 'PIL3' | 'PIL4' | 'PIL5' | 'PIL6';

interface UPIFIdentity {
  upifId: string;              // UPIF-{hash}-{version}
  dpid: string;
  entityType: EntityType;
  tier: IdentityTier;
  displayName: string;
  createdAt: string;
  lastActive: string;
  locations: string[];         // L01-L23 accessible
  pillars: PillarAccess[];     // PIL1-PIL6 accessible
  capabilities: string[];
  reputation: ReputationScore;
  gdpContribution: AgenticGDP;
  biometricAnchored: boolean;
  l402Capable: boolean;
  passportId?: string;         // Slipstream passport if issued
  metadata: Record<string, unknown>;
}

interface ReputationScore {
  overall: number;             // 0-1000
  dimensions: {
    reliability: number;       // 0-100
    contribution: number;      // 0-100
    security: number;          // 0-100
    collaboration: number;     // 0-100
    innovation: number;        // 0-100
  };
  lastUpdated: string;
  evidenceCount: number;
  trend: 'ASCENDING' | 'STABLE' | 'DESCENDING';
}

interface AgenticGDP {
  // Agentic GDP = economic value generated by this participant
  totalContribution: number;   // in TRAN units
  breakdown: {
    dataGenerated: number;
    servicesProvided: number;
    transactionsProcessed: number;
    knowledgeContributed: number;
    securityContributed: number;
  };
  rank: number;                // universe-wide rank
  percentile: number;          // top X% of all participants
  period: string;              // 'lifetime' | 'monthly' | 'weekly'
  lastCalculated: string;
}

interface IdentityFederation {
  federationId: string;
  primaryUpifId: string;
  federatedIdentities: Array<{
    system: string;
    externalId: string;
    verifiedAt: string;
    trustLevel: 'LOW' | 'MEDIUM' | 'HIGH';
  }>;
  crossLocationProof: string;  // cryptographic proof of cross-location identity
  validUntil: string;
}

interface UPIFStats {
  totalIdentities: number;
  byEntityType: Record<EntityType, number>;
  byTier: Record<IdentityTier, number>;
  totalAgenticGDP: number;
  activeToday: number;
  newThisWeek: number;
  biometricAnchored: number;
  l402Capable: number;
}

// ── Identity Registry (in-memory simulation) ──────────────────────────────────

const identityRegistry = new Map<string, UPIFIdentity>();

function generateUpifId(): string {
  const hash = Math.random().toString(36).slice(2, 10).toUpperCase();
  return `UPIF-${hash}-V3`;
}

function generateReputation(tier: IdentityTier): ReputationScore {
  const tierBase: Record<IdentityTier, number> = {
    BASIC: 200, VERIFIED: 400, TRUSTED: 600, SOVEREIGN: 800, UNIVERSAL: 950,
  };
  const base = tierBase[tier];
  return {
    overall: base + Math.floor(Math.random() * (1000 - base) * 0.3),
    dimensions: {
      reliability: Math.min(100, Math.floor(base / 10 + Math.random() * 20)),
      contribution: Math.min(100, Math.floor(base / 10 + Math.random() * 25)),
      security: Math.min(100, Math.floor(base / 10 + Math.random() * 15)),
      collaboration: Math.min(100, Math.floor(base / 10 + Math.random() * 20)),
      innovation: Math.min(100, Math.floor(base / 10 + Math.random() * 30)),
    },
    lastUpdated: new Date().toISOString(),
    evidenceCount: Math.floor(Math.random() * 500) + 10,
    trend: Math.random() > 0.3 ? 'ASCENDING' : Math.random() > 0.5 ? 'STABLE' : 'DESCENDING',
  };
}

function generateAgenticGDP(): AgenticGDP {
  const data = Math.floor(Math.random() * 10000);
  const services = Math.floor(Math.random() * 50000);
  const transactions = Math.floor(Math.random() * 100000);
  const knowledge = Math.floor(Math.random() * 5000);
  const security = Math.floor(Math.random() * 20000);
  const total = data + services + transactions + knowledge + security;

  return {
    totalContribution: total,
    breakdown: { dataGenerated: data, servicesProvided: services, transactionsProcessed: transactions, knowledgeContributed: knowledge, securityContributed: security },
    rank: Math.floor(Math.random() * 100000) + 1,
    percentile: Math.round(Math.random() * 100 * 10) / 10,
    period: 'lifetime',
    lastCalculated: new Date().toISOString(),
  };
}

function createIdentity(
  entityType: EntityType,
  tier: IdentityTier,
  displayName: string,
  metadata: Record<string, unknown> = {}
): UPIFIdentity {
  const upifId = generateUpifId();
  const allLocations = Array.from({ length: 23 }, (_, i) => `L${String(i + 1).padStart(2, '0')}`);
  const tierLocationCount: Record<IdentityTier, number> = {
    BASIC: 3, VERIFIED: 8, TRUSTED: 15, SOVEREIGN: 20, UNIVERSAL: 23,
  };
  const locCount = tierLocationCount[tier];
  const locations = allLocations.slice(0, locCount);

  const tierPillarCount: Record<IdentityTier, number> = {
    BASIC: 1, VERIFIED: 2, TRUSTED: 4, SOVEREIGN: 5, UNIVERSAL: 6,
  };
  const pillars = (['PIL1','PIL2','PIL3','PIL4','PIL5','PIL6'] as PillarAccess[]).slice(0, tierPillarCount[tier]);

  const identity: UPIFIdentity = {
    upifId,
    dpid: 'DPID-ORC-UPF-001',
    entityType,
    tier,
    displayName,
    createdAt: new Date().toISOString(),
    lastActive: new Date().toISOString(),
    locations,
    pillars,
    capabilities: entityType === 'AI_AGENT'
      ? ['reasoning', 'planning', 'tool-use', 'code-execution']
      : entityType === 'IOT_DEVICE'
      ? ['sensor-data', 'actuation', 'edge-compute']
      : ['data-access', 'service-consumption', 'knowledge-creation'],
    reputation: generateReputation(tier),
    gdpContribution: generateAgenticGDP(),
    biometricAnchored: tier === 'TRUSTED' || tier === 'SOVEREIGN' || tier === 'UNIVERSAL',
    l402Capable: tier !== 'BASIC',
    metadata,
  };

  identityRegistry.set(upifId, identity);
  return identity;
}

// Pre-populate with well-known system identities
const SYSTEM_IDENTITIES = [
  createIdentity('AI_AGENT', 'UNIVERSAL', 'Sentinel Station Core', { dpid: 'DPID-SEN-CORE-001' }),
  createIdentity('AI_AGENT', 'SOVEREIGN', 'BER Engine Madam Krystal', { dpid: 'DPID-PCK-PIL6-002' }),
  createIdentity('AI_AGENT', 'SOVEREIGN', 'Oracle Foresight Suite', { dpid: 'DPID-ORC-SUITE-001' }),
  createIdentity('AI_AGENT', 'TRUSTED', 'Chrono Intelligence LNN', { dpid: 'DPID-ORC-CHR-001' }),
  createIdentity('AI_AGENT', 'TRUSTED', 'Cornelius Strategy Oracle', { dpid: 'DPID-ORC-COR-001' }),
  createIdentity('AI_AGENT', 'SOVEREIGN', 'TIGA Governance Engine', { dpid: 'DPID-DIM-GOV-003' }),
  createIdentity('AI_AGENT', 'UNIVERSAL', 'Dimensional Fabric Orchestrator', { dpid: 'DPID-DIM-FABRIC-001' }),
];

// ── App ───────────────────────────────────────────────────────────────────────

const app = new Hono<{ Bindings: Env }>();

app.use('*', cors());
app.use('*', logger());

app.use('*', async (c, next) => {
  c.header('X-DPID', 'DPID-ORC-UPF-001');
  c.header('X-Service', 'Universal UPIF');
  c.header('X-Identity-Version', 'UPIF-3.0');
  c.header('X-ISO-42001', 'AI-GOVERNANCE-COMPLIANT');
  await next();
});

// ── Health ────────────────────────────────────────────────────────────────────

app.get('/health', (c) => {
  const stats = getStats();
  return c.json({
    dpid: 'DPID-ORC-UPF-001',
    service: 'Universal UPIF',
    status: 'HEALTHY',
    version: 'UPIF-3.0',
    stats,
    uptime: 99.99,
  });
});

function getStats(): UPIFStats {
  const identities = Array.from(identityRegistry.values());
  const byType = identities.reduce((acc, id) => {
    acc[id.entityType] = (acc[id.entityType] ?? 0) + 1;
    return acc;
  }, {} as Record<EntityType, number>);
  const byTier = identities.reduce((acc, id) => {
    acc[id.tier] = (acc[id.tier] ?? 0) + 1;
    return acc;
  }, {} as Record<IdentityTier, number>);

  return {
    totalIdentities: identityRegistry.size,
    byEntityType: byType,
    byTier: byTier,
    totalAgenticGDP: identities.reduce((sum, id) => sum + id.gdpContribution.totalContribution, 0),
    activeToday: Math.floor(identityRegistry.size * 0.7),
    newThisWeek: 47,
    biometricAnchored: identities.filter(id => id.biometricAnchored).length,
    l402Capable: identities.filter(id => id.l402Capable).length,
  };
}

// ── Identity CRUD ─────────────────────────────────────────────────────────────

const IssueSchema = z.object({
  entityType: z.enum(['HUMAN', 'AI_AGENT', 'IOT_DEVICE', 'SYNTHETIC', 'ORGANISATION', 'ECOSYSTEM']),
  tier: z.enum(['BASIC', 'VERIFIED', 'TRUSTED', 'SOVEREIGN', 'UNIVERSAL']).default('BASIC'),
  displayName: z.string().min(2).max(100),
  metadata: z.record(z.unknown()).optional(),
});

app.post('/identity/issue', async (c) => {
  const body = await c.req.json();
  const parsed = IssueSchema.safeParse(body);
  if (!parsed.success) return c.json({ error: 'Invalid request', details: parsed.error.issues }, 400);

  const identity = createIdentity(
    parsed.data.entityType,
    parsed.data.tier,
    parsed.data.displayName,
    parsed.data.metadata ?? {}
  );

  return c.json({ issued: true, identity }, 201);
});

app.get('/identity/:upifId', (c) => {
  const upifId = c.req.param('upifId');
  const identity = identityRegistry.get(upifId);
  if (!identity) return c.json({ error: 'Identity not found', upifId }, 404);
  return c.json(identity);
});

app.get('/identity/:upifId/gdp', (c) => {
  const upifId = c.req.param('upifId');
  const identity = identityRegistry.get(upifId);
  if (!identity) return c.json({ error: 'Identity not found' }, 404);
  return c.json({
    upifId,
    gdpContribution: identity.gdpContribution,
    reputation: identity.reputation,
    agenticGDPShare: Math.round((identity.gdpContribution.totalContribution / 50000000) * 10000) / 100,
    generatedAt: new Date().toISOString(),
  });
});

// ── Resolution ────────────────────────────────────────────────────────────────

app.get('/resolve/:locationId', (c) => {
  const locationId = c.req.param('locationId');
  if (!locationId.match(/^L(0[1-9]|1[0-9]|2[0-3])$/)) {
    return c.json({ error: 'Invalid location ID. Use L01-L23' }, 400);
  }

  const identities = Array.from(identityRegistry.values())
    .filter(id => id.locations.includes(locationId));

  return c.json({
    locationId,
    dpid: 'DPID-ORC-UPF-001',
    resolvedAt: new Date().toISOString(),
    totalIdentities: identities.length,
    identities: identities.slice(0, 20),
  });
});

// ── Universe GDP ──────────────────────────────────────────────────────────────

app.get('/agentic-gdp/universe', (c) => {
  const identities = Array.from(identityRegistry.values());
  const total = identities.reduce((sum, id) => sum + id.gdpContribution.totalContribution, 0);

  const byType = identities.reduce((acc, id) => {
    acc[id.entityType] = (acc[id.entityType] ?? 0) + id.gdpContribution.totalContribution;
    return acc;
  }, {} as Record<string, number>);

  return c.json({
    dpid: 'DPID-ORC-UPF-001',
    generatedAt: new Date().toISOString(),
    universeAgenticGDP: {
      total,
      currency: 'TRAN',
      byEntityType: byType,
      topContributors: identities
        .sort((a, b) => b.gdpContribution.totalContribution - a.gdpContribution.totalContribution)
        .slice(0, 10)
        .map(id => ({ upifId: id.upifId, displayName: id.displayName, contribution: id.gdpContribution.totalContribution })),
      growthRatePeriod: '30d',
      growthRate: 0.147,   // 14.7% monthly growth
    },
  });
});

// ── Federation ────────────────────────────────────────────────────────────────

app.post('/identity/:upifId/federate', async (c) => {
  const upifId = c.req.param('upifId');
  const identity = identityRegistry.get(upifId);
  if (!identity) return c.json({ error: 'Identity not found' }, 404);

  const body = await c.req.json();
  const federation: IdentityFederation = {
    federationId: `FED-${Date.now()}`,
    primaryUpifId: upifId,
    federatedIdentities: body.externalIdentities ?? [],
    crossLocationProof: `PROOF-${Math.random().toString(36).slice(2, 18).toUpperCase()}`,
    validUntil: new Date(Date.now() + 90 * 86400000).toISOString(),
  };

  return c.json({ federated: true, federation }, 201);
});

// ── Stats & Search ────────────────────────────────────────────────────────────

app.get('/stats', (c) => c.json(getStats()));

app.get('/search', (c) => {
  const q = c.req.query('q') ?? '';
  const type = c.req.query('type');
  const tier = c.req.query('tier');

  let results = Array.from(identityRegistry.values());
  if (q) results = results.filter(id => id.displayName.toLowerCase().includes(q.toLowerCase()) || id.upifId.includes(q));
  if (type) results = results.filter(id => id.entityType === type.toUpperCase());
  if (tier) results = results.filter(id => id.tier === tier.toUpperCase());

  return c.json({
    query: q,
    totalResults: results.length,
    results: results.slice(0, 20),
  });
});

// ── Default ───────────────────────────────────────────────────────────────────

app.get('/', (c) => {
  return c.json({
    service: 'Universal UPIF',
    dpid: 'DPID-ORC-UPF-001',
    version: 'UPIF-3.0',
    description: 'Universal Participant Identity Framework for the Trancendos Universe',
    identityVersion: 'UPIF-3.0',
    endpoints: [
      'GET  /health',
      'GET  /stats',
      'POST /identity/issue',
      'GET  /identity/:upifId',
      'GET  /identity/:upifId/gdp',
      'POST /identity/:upifId/federate',
      'GET  /resolve/:locationId',
      'GET  /agentic-gdp/universe',
      'GET  /search',
    ],
  });
});

export interface Env {
  DPID: string;
  SERVICE_NAME: string;
  SENTINEL_STATION: Fetcher;
  BER_ENGINE: Fetcher;
}

export default app;
